
version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    hostname: filebrowser
    restart: always
    networks:
      - proxy
    volumes:
      - ./config/filebrowser:/config
      - /:/srv
    environment:
      - PHP_TZ=Europe/London
      - PUID=666
      - PGID=666
      - VIRTUAL_HOST=filebrowser.pknw1.co.uk
      - VIRTUAL_PORT=80

networks:
  proxy:
    external:
      name: proxy
