
version: '3'

services:
  ifm:
    image: pknw1/ifm:latest
    container_name: ifm
    hostname: ifm
    restart: always
    networks:
      - proxy
    volumes:
      - ./config/ifm:/config
      - /content/movies:/var/www/media/movies:ro
      - /content/tv:/var/www/media/tv:ro
      - /content/software:/var/www/software:ro
      - /content/youtube:/var/www/media/youtube:ro
      - /content/education:/var/www/education:ro
      - /content/comedy:/var/www/media/comedy:ro
      - /download/movies:/var/www/download/movies:ro
      - /download/tv:/var/www/download/tv:ro
      - /download/education:/var/www/download/education:ro
      - /download/software:/var/www/download/software:ro
      - /download/youtube:/var/www/download/youtube:ro
      - /download/upload:/var/www/upload:rw
    environment:
      - PHP_TZ=Europe/London
      - PUID=666
      - PGID=666
      - VIRTUAL_HOST=download.pknw1.co.uk
      - VIRTUAL_PORT=80

networks:
  proxy:
    external:
      name: proxy
