
version: '3'

services:
  jellyfinod:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfinod
    hostname: jellyfinod
    restart: always
    networks:
      - proxy
    volumes:
      - ./config/jellyfinod:/config
      - /:/host
    environment:
      - PHP_TZ=Europe/London
      - PUID=666
      - PGID=666
      - VIRTUAL_HOST=jellyfin2-ondemand.pknw1.co.uk
      - VIRTUAL_PORT=8096

networks:
  proxy:
    external:
      name: proxy
