
version: '3'

services:
  kitana:
    image: pannal/kitana
    container_name: kitana
    hostname: kitana
    restart: always
    ports:
      - 31337:31337
    networks:
      - proxy
    volumes:
      - ./config/kitana:/app/data
      - /:/host
    environment:
      - PHP_TZ=Europe/London
      - PUID=666
      - PGID=666
      - VIRTUAL_HOST=kitana.pknw1.co.uk
      - VIRTUAL_PORT=31337
    command: -B 0.0.0.0:31337 -p / -P

networks:
  proxy:
    external:
      name: proxy
