version: "3"

services:
  piholeint:
    container_name: pihole-int
    image: pihole/pihole:latest
    ports:
      - "172.18.0.1:53:53/tcp"
      - "172.18.0.1:53:53/udp"
      - "172.18.0.1:67:67/udp"
    dns:
      - 8.8.8.8
    volumes:
      - ./config/pihole-int/etc-pihole/:/etc/pihole/
      - ./config/pihole-int/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - WEBPASSWORD=C0nduit32
      - TZ=Europe/London
      - PUID=666
      - PGID=666
      - VIRTUAL_HOST=pihole-int.pknw1.co.uk
      - VIRTUAL_PORT=80

networks:
  proxy:
    external:
      name: proxy
