
version: '3'

services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    hostname: tautulli
    restart: always
    ports:
      - 8181:8181
    networks:
      - proxy
    volumes:
      - ./config/tautulli:/config
      - /tmp/tautulli-newsletters:/config/newsletters:shared
      - /:/host
    environment:
      - PHP_TZ=Europe/London
      - PUID=666
      - PGID=666
      - VIRTUAL_HOST=tautulli.pknw1.co.uk
      - VIRTUAL_PORT=8181

networks:
  proxy:
    external:
      name: proxy
