
version: '3'

services:
  watchtower:
    image:  containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: always
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/watchtower:/config
    environment:
      - PHP_TZ=Europe/London
      - PUID=666
      - PGID=666
      - REPO_USER=pknw1
      - REPO_PASS=pk020668000
    command: --interval 90


networks:
  proxy:
    external:
      name: proxy
